- src/components/Button/Button.tsx
- src/pages/index.tsx
This PR contains.
- Primary button with colors and transitions
- Secondary button with colors and transitions
> primary and secondary button are done

- src/components/Inputfields/Inputfield.stories.ts
- src/components/Inputfields/Inputfield.tsx
- src/components/Inputfields/label.tsx
- src/pages/index.tsx
This PR contains the following changes:
- Input field styled according to figma file
- Transitions on select and deselect 
- label created
> Inputfield with label done

- src/components/Textarea/Textarea.stories.ts
- src/components/Textarea/textarea.tsx
- src/pages/index.tsx
This PR contains the following changes:
- Message field created
- Transition when selecting and delecting
- Placeholder and labels
> Message field done

- src/modules/Header/Header.tsx
- src/styles/globals.css
- set position to fixed and z-index to 10, so stuff can go behind ;) 
- changed transparency from 50% to 70%
> Updates to header

- src/Layout.tsx
- src/pages/booking.tsx
- src/pages/events.tsx
- src/pages/events/firma-events.tsx
- src/pages/events/foedselsdag.tsx
- src/pages/events/turneringer.tsx
- src/pages/om-os.tsx
- src/pages/om-os/kontakt.tsx
- src/pages/priser.tsx
i have created all pages, so they are ready to be build
> added all pages

- src/modules/Header/Header.tsx
- added wrapper to line up with rest of content
- added overflow scroll to mobile menu to make sure it works in horizontal view
> added wrapper for nav in order to use padding

- src/modules/Footer/Footer.tsx
- src/modules/Header/Header.tsx
- src/modules/Hero/Hero.tsx
- src/styles/globals.css
Jeg har tilføjet en class, der hedder .spacer. Dens formål er at vi kan bruge den til at putte på vores containere, så de allesammen kommer til at have den samme afstand til siderne og til det forlæggende component.
> added spacer class

- src/modules/Hero/Hero.tsx
- src/pages/_document.tsx
- src/pages/index.tsx
- src/pages/priser.tsx
- src/styles/globals.css
Der var før en masse problemer med responsiviteten af disse to sider, men dette skulle nu være fixet med denne pr.
> Forside og Priser gjort mere responsive

- package-lock.json
- src/components/NavLinkDropDown/NavLinkDropDown.tsx
- src/styles/globals.css
Når man hover menupunkt med sub-menu, var der et lille gap i mellem punktet og menuen hvor den ikke var åben. (se video for forklaring)
Det er rettet nu med en "py-4" på <a> tag som har submenu.
Har tilføjet <li> om menupunkter for semantik
max-w-screen-xl --> mx-w-main i stedet for. 
https://github.com/TobiasRoland123/next_level/assets/99641671/438a07ea-8f38-4ff7-b4c3-2b9f9e2a07be
> Fixed header issue with hover

- package-lock.json
- src/Layout.tsx
- src/Layout_Admin.tsx
- src/components/Button/Button.tsx
- src/modules/AdminHeader/AdminHeader.stories.ts
- src/modules/AdminHeader/AdminHeader.tsx
- src/pages/_app.tsx
- src/pages/admin/booking.tsx
- src/pages/admin/index.tsx
- src/pages/admin/spil.tsx
- src/pages/booking.tsx
- src/pages/events.tsx
- src/pages/events/firma-events.tsx
- src/pages/events/foedselsdag.tsx
- src/pages/events/turneringer.tsx
- src/pages/index.tsx
- src/pages/login.tsx
- src/pages/om-os.tsx
- src/pages/om-os/kontakt.tsx
- src/pages/priser.tsx
- src/pages/spil.tsx
- src/styles/globals.css
- Removed `<Layout>` from _app
- Added `<Layout>` + `<main>` to all pages
- Added ´min-height: calc(100vh-368px)`to `<main>`in `global.scc` so that the main will always fill out, but the footer will be at the bottom. om the page. 
- Made `<AdminHeader>` component and `Layout_Admin.tsx` for the admin pages
- Added `onClick` property to `<Button>`
- Links in `<Header>` dit not work properly (
**Expectet outcome**: If you were on page `/events/turneringer` and pressed on `spil` in the header, you would go to `/spil`
**Behavior**: If you are on page `/events/turneringer` and press on `spil` in the header, you go to `/events/spil`
**Fix**: Changed `href="./*"` to be `href="../*"`
> Feature change layout from app to all pages

- src/components/Cards/Card.tsx
- src/modules/Header/Header.tsx
- src/pages/index.tsx
price cards added to front page
> Feature frontpage adding price cards

- src/modules/Footer/Footer.tsx
- src/modules/Header/Header.tsx
- tailwind.config.ts
I have changed the button in the header on mobile to be basic html button instead of our custom button, because we dont need the styling from our button.
> Hotfix header mobile button styling issue

- src/modules/Header/Header.tsx
- tailwind.config.ts
added max-width on header and changed max-w-main to 1280 instead of 1250px to make it follow design
> hotfix_added-max-width-on-main

- src/components/Cards/Card.tsx
- src/modules/EventBanner/EventBanner.tsx
- src/modules/Hero/Hero.stories.tsx
- src/modules/Hero/Hero.tsx
- src/pages/events.tsx
- src/pages/events/firma-events.tsx
- src/pages/events/foedselsdag.tsx
- src/pages/events/turneringer.tsx
- src/pages/index.tsx
- src/pages/priser.tsx
- src/styles/globals.css
- NLP kortet har krævet en del ændringer da det ikke var lavet mobile first, så det er derfor der er så mange ændringer i denne fil.
> Priser siden er Done

- src/modules/Header/Header.tsx
navbar and mobile menu now has higher z-index than cards
> changed z-index on header to be higher than cards

- src/modules/Hero/Hero.tsx
> changed path to HyphenatedText in Hero

- package-lock.json
- src/components/Cards/Card.tsx
- src/components/InputDatePicker/InputDatePicker.tsx
- src/components/Select/SelectField.tsx
- src/components/ui/button.tsx
- src/components/ui/calendar.tsx
- src/modules/Forms/Contactform/ContactForm.tsx
- src/pages/login.tsx
- src/pages/om-os/kontakt.tsx
This PR contains a massive amount of rad shit that too difficult to actually explain. But i'll try.
I have implemented the following:
- Validation on the login page along with some sick animations to spice things up. This shit is off the chain!
- Redirect from the NLP card to contact with scroll to form with nlp selected as subject. 
- You can now pick a date that's being thrown into the message object on fødselsdag, firma-event and nlp. This field is also obligatory since people are idiots and can't figure out to write a message requesting something, even if their lives depended on it. The date is being validated as well.
- Added ts-ignore on most of the type errors in ContactForm. Shit was working but Typescript was being an asshole for no reason. 
- Probably some other shit I can't …
> Feature datepicker validation

- .idea/.gitignore
- .idea/modules.xml
- .idea/next_level.iml
- .idea/vcs.xml
- src/components/ui/popover.tsx
there was an import in popover making problems for storybook
> fixed popover import issue

- src/pages/om-os.tsx
> video on om os side

- src/components/Inputfields/Inputfield.tsx
- src/modules/Header/Header.tsx
updated links in header suckers
> added links to book button in header

- src/components/BookedTimeSlot/BookedTimeSlot.tsx
- src/modules/Forms/Contactform/ContactForm.tsx
- src/pages/booking.tsx
> fixed import errors for components and modules that was using @

- src/modules/AdminHeader/AdminHeader.tsx
- src/pages/admin/index.tsx
fixed mobile menu button in header on admin
> changed button in header

- src/components/AddGameSheet/AddGameSheet.tsx
- src/components/BookedTimeSlot/BookedTimeSlot.tsx
- src/components/Calender/DatePicker.tsx
- src/components/Cards/Card.tsx
- src/components/EditGameSheet/EditGameSheet.tsx
- src/components/Select/SelectField.stories.ts
- src/modules/AdminHeader/AdminHeader.tsx
- src/modules/BookingForm/BookingForm.tsx
- src/modules/Forms/Contactform/ContactForm.stories.ts
- src/modules/Forms/Contactform/ContactForm.tsx
- src/modules/GameListAdmin/SpilListe.tsx
- src/pages/admin/booking.tsx
- src/pages/api/gamelist.js
- src/pages/booking.tsx
- src/pages/om-os/kontakt.tsx
- src/pages/spil.tsx
Booking system fungerer og jeg har fjernet console.logs
> Book 5 pc's if not all pc's are booket + removed console.log

- src/modules/AdminHeader/AdminHeader.tsx
> z-index works
